NumPy

In [1]:
from platform import python_version
print('Versão da linguagem python usada', python_version())

Versão da linguagem python usada 3.9.12


In [18]:
#Instalação do pacote watermark
#É usado para marcar as versões de outros pacotes usado neste jupter notebook
!pip install -q -U watermark

ERROR: Could not install packages due to an OSError: Proxy URL had no scheme, should start with http:// or https://



In [ ]:
import numpy as np

### Criando estrutura de dados com numpy

In [14]:
# Criando array unidimensional
array1 = np.array([10,20,30,40])

In [15]:
print(array1)

[10 20 30 40]


In [16]:
# verificando o formato (shape) do array
array1.shape

(4,)

In [17]:
# Verificando o número de dimensões 
array1.ndim

1

In [21]:
# Criando array bi-dimensional
array2 = np.array([[10,20,30], [15, 25, 35]])

In [22]:
# verificando o formato (shape) do array
array2.shape

(2, 3)

In [25]:
# Verificando o número de dimensões 
array2.ndim

2

In [26]:
#metodo
array2.max()

35

In [27]:
#atributo
array2.ndim

2

#### Criando estrutura de dados com função Arange

In [29]:
array3 = np.arange(14)

In [30]:
array3

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13])

In [31]:
# usando start/end (exclusive)
array4 = np.arange(0,15, 3)

In [32]:
array4

array([ 0,  3,  6,  9, 12])

#### Criando estrutura de dados com linspace

In [35]:
# Arguments (start, end, number of elements)
array5 = np.linspace(0,3,4)
array5

array([0., 1., 2., 3.])

#### Criando estrutura de dados com outras funções

In [37]:
# numpy.zeros
# Array 3x3 de zeros
array6 = np.zeros([3,3])
array6

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [38]:
# numpy.ones
# Array 3x3 de 1's
array7 = np.ones([3,3])
array7

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [40]:
# numpy.eye
# Produz uma matriz identididade
array8 = np.eye(3)
array8

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

Quando falamos em matrizes identidades, nos referimos às matrizes quadradas, cujos elementos da diagonal principal é 1 e os demais elementos são todos zeros.



In [41]:
# numpy.diag
# Matriz diagonal
array9 = np.diag((2,1,4,6))
array9

array([[2, 0, 0, 0],
       [0, 1, 0, 0],
       [0, 0, 4, 0],
       [0, 0, 0, 6]])

matriz quadrada em que todos os elementos que não estão na diagonal principal são nulos.

In [43]:
# numpy.random.rand
# A função rand(n) produz uma sequencia de números uniformemente distribuidos com range de zero a n
np.random.seed(100) #set seed - permite executar o processo aleatório seguindo o msm padrão
array10 = np.random.rand(5)
array10

array([0.54340494, 0.27836939, 0.42451759, 0.84477613, 0.00471886])

In [45]:
# A função randn(n) produz uma sequencia de número com distribuição normal gaussian
array11 = np.random.randn(5)
array11

array([ 0.17957831, -0.5771615 , -0.53337271, -0.22540212, -0.31491934])

In [47]:
array12 = np.empty((2,2))
array12

array([[1.e-323, 5.e-324],
       [2.e-323, 3.e-323]])

In [50]:
# numpy.tile
array13 = np.array([[1,2],[3,4]])
array13

array([[1, 2],
       [3, 4]])

In [51]:
np.tile(np.array([[1,2],[3,4]]), 4)

array([[1, 2, 1, 2, 1, 2, 1, 2],
       [3, 4, 3, 4, 3, 4, 3, 4]])

In [52]:
np.tile(np.array([[1,2],[3,4]]),(2,2))

array([[1, 2, 1, 2],
       [3, 4, 3, 4],
       [1, 2, 1, 2],
       [3, 4, 3, 4]])